name: VanillaElytra
softdepend: Firework
main: JavierLeon9966\VanillaElytra\VanillaElytra
author: JavierLeon9966
version: 1.4.0
api: 5.0.0
mcpe-protocol: [527, 534, 544]
description: A plugin that implements vanilla Elytra into PocketMine-MP
